package clientserveurweb.client.UI;

import clientserveurweb.client.Core.Client;
import clientserveurweb.client.Core.Observers.ClientObserver;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * Web browser UI class
 *
 * @author Adrien
 */
public class ClientMainFrame extends javax.swing.JFrame implements ClientObserver {

    /**
     * User of the browser
     */
    private Client _client;

    public static final int DEFAULT_PORT = 80;

    /**
     * Creates new form ClientMainFrame
     */
    public ClientMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jMainTextPane = new javax.swing.JTextPane();
        jURL = new javax.swing.JTextField();
        jCharger = new javax.swing.JButton();
        jQuitter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Navigateur Web");

        jMainTextPane.setEditable(false);
        jScrollPane1.setViewportView(jMainTextPane);

        jURL.setText("http://127.0.0.1/index.html");

        jCharger.setText("Charger la page");
        jCharger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChargerMouseClicked(evt);
            }
        });

        jQuitter.setText("Quitter");
        jQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jQuitterMouseClicked(evt);
            }
        });

        jEditorPane.setEditable(false);
        jEditorPane.setContentType("text/html");
        jScrollPane2.setViewportView(jEditorPane);

        jLabel1.setText("URL :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jURL, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCharger)
                        .addGap(66, 66, 66)
                        .addComponent(jQuitter)
                        .addGap(0, 237, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQuitter)
                    .addComponent(jCharger)
                    .addComponent(jURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jQuitterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jQuitterMouseClicked

    private void jChargerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChargerMouseClicked
        if (jURL.getText().length() > 0) {
            try {
                //Connection check
                //If the connection was never established
               // if (_client != null) {
                    //Create a new Client session
                    _client = new Client(DEFAULT_PORT, new URL(jURL.getText()));
                    _client.addClientObserver(this);
                /*} else {
                    //Else get the URL
                    _client.setGet(new URL(jURL.getText()));
                }*/

                Thread processusClient = new Thread(_client);
                processusClient.start();
            } catch (MalformedURLException ex) {
                jMainTextPane.setText("URL incorrect");
            }
        } else {
            jMainTextPane.setText("Champ d'URL vide");
        }
    }//GEN-LAST:event_jChargerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCharger;
    private javax.swing.JEditorPane jEditorPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextPane jMainTextPane;
    private javax.swing.JButton jQuitter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jURL;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onResponseContent(String str, String contentType) {
        jEditorPane.setContentType("text/html");
        jEditorPane.setText(str);
    }

    @Override
    public void onTextResponse(String str) {

        jMainTextPane.setText(str);
    }
}
